Edit KontaktSkjemaHandler to set dummy account
navikt/crm-arbeidsgiver-integration pull request #96
Opened 2021-05-26 10:11 UTC by raac09

2021-05-27 11:44 UTC, johnforeland requested changes

2021-05-27 13:11 UTC, raac09 commented on force-app/main/kontaktskjema/classes/KontaktSkjemaHandler.cls
> +                accountId = dummyAccount.size() > 0 ? dummyAccount[0].Id : null;
endret

2021-05-27 13:11 UTC, raac09 commented on force-app/main/kontaktskjema/classes/KontaktSkjemaHandler.cls
> +                update currentContact;
endret

2021-05-28 07:30 UTC, johnforeland requested changes

2021-05-28 07:30 UTC, johnforeland commented on force-app/main/kontaktskjema/classes/KontaktSkjemaHandler.cls
> +        }
```suggestion
        Boolean missingOrgNo = String.isBlank(rw.organisationNumber);
        Id accountId = missingOrgNo ? null : getAccount(rw.organisationNumber);

        // If no organization number is missing, update contact with dummy account
        if (missingOrgNo) {
            updateContactWithNewAccount(contactId, accountId);                
        }
```

Dette var min feil fordi jeg foreslo det forrige gang. Men testet du løsningen som jeg foreslo? Fordi hadde du det hadde du nok sett at alle muligheter uten org-nr hadde fått "kontakter uten konto" som konto på MULIGHETEN.

2021-05-28 07:30 UTC, johnforeland commented on force-app/main/kontaktskjema/classes/KontaktSkjemaHandlerTest.cls
```suggestion

@isTest
private static void accountIsEmptyWhenOrgNoMissing() {
}

```

Ønsker at du lager denne testen og sørger for at den blir rød, før du fikser feilen med at "Kontakter uten konto" blir satt direkte på muligheten.

2021-05-28 07:30 UTC, johnforeland commented on force-app/main/kontaktskjema/classes/KontaktSkjemaHandlerTest.cls
>      @isTest // ! tests the Opportunity process to make sure contacts receive an account after adding an account manually to the opty (happens if a user does not input org number in the web form)
```suggestion

@isTest
private static void testUpdateContactWithNewAccount_existingAccount() {
}

    @isTest // ! tests the Opportunity process to make sure contacts receive an account after adding an account manually to the opty (happens if a user does not input org number in the web form)
```

Ønsker du lager denne testen også, fordi jeg mistenker at dette vil skje (og det skal det jo ikke). Den skal teste at man har allerede en kontakt i Salesforce med knytning til Account, så sender man inn mulighet uten org-nr. Da skal jo nye kontakter får "Kontakter uten konto", men denne kontakten har jo faktisk en konto fra før (fordi `fetchOrCreateContact` matcher på e-posten).

2021-05-28 07:42 UTC, raac09 commented on force-app/main/kontaktskjema/classes/KontaktSkjemaHandler.cls
> +        }
Testet ikke det du nevner her nei

2021-06-03 14:12 UTC, johnforeland approved these changes

2021-06-04 08:45 UTC, merged